### ISSUE TITLE
Code Snippet: Subscribe users based on editorial metadata checkbox status

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#113]
[The use case](http://wordpress.org/support/topic/plugin-edit-flow-notifications-depending-on-post-status-and-metadata) is as follows:

"1) When a post is submitted for approval, I need the editors to be notified. I will use metadata to insert two check boxes (one for each of our two editing stages). When an editor has done their part, they will tick their check box. When both check boxes are ticked...

2) I need to be notified for finally approval and scheduling.

So, I need the basic notification set up for editors when the status changes to Pending and I need something that will check the status of the two check boxes whenever a post is saved and notify me when they are both ticked."

**Comment by WPprodigy** [comment]
I agree that post statuses make the most sense for this type of flow.

Closing this for now.
