### ISSUE TITLE
New feature: Ideas Bin

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#189]
@bbrooks and @natebot will be working on a new feature for v0.9: The ideas bin.

The goal of this feature is to make it easier for editorial staff (and possibly community) to pitch and keep a database of story ideas. The priorities we discussed are:
- Story ideas should be restricted in length, so they don't become full-fledged posts.
- It should be possible to comment on story ideas with editorial comments, and possibly vote.
- Story ideas will be a custom post type, so they don't clutter up other parts of the WordPress admin.

I think we should hit wireframes / mockups first, and then we can start working on code.

**Comment by joshuarrrr** [comment]
@danielbachhuber You might want to look at how camayak handles pitches vs assignments, and converting from one to the other. It's at least one working model of what you're talking about.

https://www.youtube.com/watch?v=6xsqnDhWe2A
