### ISSUE TITLE
Pagination on multi page posts broken in Preview Mode

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#192]
Reported in the forums: http://wordpress.org/support/topic/pagination-on-multi-page-posts-not-working-in-preview-mode

**Comment by danls** [comment]
Can confirm this issue still persists. Pagination is broken when a post is set to one of the custom status types provided by Edit Flow. Setting it back to Draft restores pagination function.

**Comment by slobodan** [comment]
Still happens with WordPress 4.1.1 and Edit Flow 0.8
