### ISSUE TITLE
Publish date remains date created instead of allowing for "Immediately" 

### ISSUE THREAD

**Issue by sararosso** [Automattic/Edit-Flow#196]
When drafting a post, if the date between creation & publishing is different, the post will often retain the creation date as the "publish time" instead of the "Publish: Immediately" default with no date/time associated with it.

If the post is scheduled, this the "default publish date" is overridden. 

I did: Drafted a post one day and published it the next. 

I expected: The post to have the date/time of actual publishing, since it wasn't scheduled. 

I saw: The post had the date of drafting. "Publish: immediately" wasn't available either during the drafting process.

**Comment by cojennin** [comment]
Superseded by #321, should be fixed by #343. Closing.
