### ISSUE TITLE
Localize the date at the top of the story budget and calendar

### ISSUE THREAD

**Issue by eniefaC** [Automattic/Edit-Flow#202]
Hi,

At the moment, when browsing to the calendar or the story budget, I get an incomplete localization "Calendrier for June 10th through July 21st"

It would be nice if the date was also translatable.

Thanks.

**Comment by raduconst** [comment]
Hey @eniefaC ! Is this problem still available? I just checked the top of the calendar page and the date is working very well now:
<img width="551" alt="screen shot 2018-01-16 at 15 57 19" src="https://user-images.githubusercontent.com/6512220/34992475-023f3cd6-fad6-11e7-9043-91cf2fac1ec3.png">
I just want to see if this is still a problem so I can get it fixed.

**Comment by eniefaC** [comment]
Hey! Thanks for getting back to me, even after such a long time! I'm not using the plugin anymore, but since I posted the issue 4 years ago, I took the time to install it again.

The version I downloaded through wordpress did not change anything.

I tried to download the latest version from Github directly, and **on the calendar page**, the name is indeed translated now:
![image](https://user-images.githubusercontent.com/1926925/35062928-e09292fe-fbc5-11e7-8594-7f66b438e659.png)

The problem still exists **on the story budget page**:
![image](https://user-images.githubusercontent.com/1926925/35062981-0a9f48da-fbc6-11e7-9af5-1a9b2c69ebaf.png)

Hope this helps and thanks again for the work you put in this plugin, it served me well!

**Comment by raduconst** [comment]
It seems that everything is fine on the code side. All it needs is an update to the POT and translation PO/MO files. That did the trick on my side. I'll regenerate these files very soon and everything should be back to normal starting with the next version of the plugin.

**Comment by eniefaC** [comment]
That is some great news! Thanks again!
