### ISSUE TITLE
Menu Icon doesn't work with MP6

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#238]
![image](https://f.cloud.github.com/assets/36432/1854688/48c8ac7a-7720-11e3-83a3-e2a607ee3b5f.png)

Too dark, unfortunately.

**Comment by raduconst** [comment]
@philipjohn What should we do here? Just replace the icon with a white one?

**Comment by justnorris** [comment]
We can probably start by inverting that icon to white, but eventually an getting an SVG replacement would be great.

**Comment by justnorris** [comment]
Submitted a pull request for this - #407 

No SVG yet, but the icon is visible now.
