### ISSUE TITLE
Columns don't reflow on the story budget when you change the number of columns displayed

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#24]
I did:
- Went to the story budget
- Changed the number of columns using screen options from one to two

I saw:
- All of the widgets stay in the first column, and shrink to half their width

I expected:
- Widgets to auto-flow to two columns

**Comment by raduconst** [comment]
I made a small change for the columns from _Story Budget_ area in #409

**Comment by TheCrowned** [comment]
Fixed in #460.

**Comment by TheCrowned** [comment]
Fixed in #460.
