### ISSUE TITLE
Uniformity in ensuring scripts/styles are embedded on the correct page

### ISSUE THREAD

**Issue by cojennin** [Automattic/Edit-Flow#240]
Be nice if we could ensure a uniform way of making sure all styles and scripts are embedded on the correct page. For instance, in the story budget we use the following to check if we're on the correct page https://github.com/Automattic/Edit-Flow/blob/master/modules/story-budget/story-budget.php#L147, while in the Calendar we check like so: https://github.com/Automattic/Edit-Flow/blob/master/modules/calendar/calendar.php#L181.

It'd be nice if there was a function to abstract and localize this checking of pages to one place (if there are going to be differences/there are going to be changes).

**Comment by philipjohn** [comment]
Closing in favour of #351
