### ISSUE TITLE
In mobile view button to update user groups is not displayed

### ISSUE THREAD

**Issue by Circleview** [Automattic/Edit-Flow#254]
If you want to update an user group with a mobile device you can do this in an mobile optimized web view, wich is great, but the button to update the user group will not be displayed. 

I checked this on iPhone 5/5s with chrome an safari. 

The screenshot is in german (#233) but hopefully my point will be clear anyway. 

![foto](https://cloud.githubusercontent.com/assets/6303048/2534753/86999966-b581-11e3-8977-3792265ce909.PNG)

**Comment by justnorris** [comment]
Reproduced the issue and found a fix! 😎
