### ISSUE TITLE
Fatal error: Call to undefined function get_current_screen()

### ISSUE THREAD

**Issue by WPMidway** [Automattic/Edit-Flow#255]
This error occurred when I was trying to update email information from a woocommerce my-account/edit-account screen as both admin and as a customer which is on the front-end.

Fatal error: Call to undefined function get_current_screen() in edit-flow/modules/user-groups/user-groups.php on line 693

Fix was made by adding to line 11 at the top: 
require_once (ABSPATH . wp-admin/includes/screen.php);

The error is not showing and appears to be fixed.

My setup is not a network site, but has multiple vendors set up, so I do not know if this is a problem with normal woocommerce sites and the use of this plugin.

**Comment by cojennin** [comment]
Should be fixed by #283. Closing.
