### ISSUE TITLE
Problem with status change notifications

### ISSUE THREAD

**Issue by slobodan** [Automattic/Edit-Flow#256]
Hi,

According to site editor, this started happening a few days ago, the only thing I can think of that happened at around that time was WP 3.8.2 update. 

Status change notification emails don't show preview link anymore, for example (see "View") when changing from one custom status to another:

```
== Actions ==

Add editorial comment: http://site.url/wp-admin/post.php?post=95247&action=edit#editorialcomments/add

Edit: http://site.url/wp-admin/post.php?post=95247&action=edit

View: ?preview=true
```

Or from Scheduled to Published:

```
== Actions ==

Add editorial comment: #editorialcomments/add

Edit:

View: http://site-url/slug/ID/
```

site.url, permalink and ID obviously changed in these code blocks.

Seems to be a problem with $view_link and $edit_link in https://github.com/Automattic/Edit-Flow/blob/419e5280bd50a1eff7a4782784740b19820d789a/modules/notifications/notifications.php#L577-L579

**Comment by cojennin** [comment]
I'm unable to recreate this issue using Edit Flow v0.8.1 and WordPress v4.5.2.

Steps to reproduce:
1. Create a new post as a user with the role "contributor"
2. Save the post with a status of "Pitch"
3. Email with correct edit and view link is sent
4. Move post from status of "Pitch" to status of "Assigned"
4. Email with correct edit and view link is sent

Are you still seeing this issue?

**Comment by slobodan** [comment]
@cojennin Sorry, I don't work with that site, or Edit Flow anymore.

**Comment by cojennin** [comment]
No worries, thanks for checking back in!

Marking as "needs-confirmation" for the time being

**Comment by cojennin** [comment]
Haven't been able to recreate this issue and the original reporter no longer works with Edit Flow. Recommending close.

**Comment by cojennin** [comment]
Haven't heard anything else about this issue so going to close. Thanks for the report, if folks notice this cropping up feel free to open up a new issue!
