### ISSUE TITLE
User groups collide with tags, categories, and other taxonomies' terms

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/Edit-Flow#26]
I haven't proved this, but I believe the user group taxonomy term slug is prefixed when the group is created, but then the prefix is dropped when the group is updated. Due to the lack of the slug argument being passed, it defaults to the sanitize_title() of the name

**Comment by sboisvert** [comment]
This shouldn't be a problem anymore because of term splitting having happened. Closing for now.
