### ISSUE TITLE
Edit Flow conflict with BuddyPress

### ISSUE THREAD

**Issue by mapofemergence** [Automattic/Edit-Flow#262]
I bumped into a pretty odd behaviour on my website, where I use both BuddyPress and EditFlow (and wouldn't give up using any of the two).

Basically whenever I have an update in a Group's activity or forum, that update won't appear in the activity's wall.
What's odd is that I was able to find those updates in the backend, but they're published "back in time" (something published today, appears as it was published on November the 30th 1999).

I'm not 100% sure that the problem is in Edit Flow, instead of BuddyPress.
What makes me doubt, still, is that BuddyPress forums are actually based on a third plugin, bbPress, which apparently is recording forum topics with the correct date; only the updates that BuddyPress generates from those have it wrong.

On the other hand, I read here and on other forums, that Edit Flow had a few bugs with the calendar (if I'm not mistaken). Then I guessed these problems might be related, mine involving wrong dates.

WordPress version: 3.9.1
EditFlow version: 0.8
BuddyPress version: 2.0.1 
bbPress version: 2.5.4 

Is this something you're aware of, or something of which you might know the cause?

Please let me know if I can help further, in any way.
Cheers,
s

**Comment by mapofemergence** [comment]
Sorry for replying that late, and thank you for looking into this.
At the time of reporting, I just realized it was related to custom-statuses and disabled that feature.
It is good to know that you have a way to workaround the issue, though.
I'll try to test the fix as soon as possible, and be back to you, hopefully in a reasonable time.

**Comment by SiteDesignUSA** [comment]
Having same issue. Any updates?
I've tried the functions route and no fix. Tried commenting out the line in the plugin but gave warnings.

**Comment by SiteDesignUSA** [comment]
My fix. I couldn't get the filter to work so I hacked the plugin file at:
plugins/edit-flow/modules/custom-status/custom-status.php

Very little testing, but seems to work. For now.

		//If the time isn't set, don't set it.
		if( empty( $_POST['aa'] ) ) {
        if ($data['post_date_gmt'] == '0000-00-00 00:00:00') {
            $data['post_date_gmt'] = $data['post_date'];
        }
		return $data;
		}

Everything seems to still work but I probably haven't hit that "fringe case" that supplied the reason for that code in the first place.

**Comment by cojennin** [comment]
Think this should be fixed by #343.

The reason for `post_date_gmt` being overwritten can be [found here](https://wordpress.org/support/topic/plugin-edit-flow-custom-statuses-create-timestamp-problem).

If folks have a few minutes to test the `master` branch of Edit Flow it'd be great to help with testing to make sure this issue is totally resolved.
