### ISSUE TITLE
Conflict Between Edit Flow and The WordPress For iOS App

### ISSUE THREAD

**Issue by TheJeffr0** [Automattic/Edit-Flow#267]
After diagnosing the problem, there seems to be a conflict between Edit Flow and the WordPress for iOS application. 

http://ios.forums.wordpress.org/topic/editing-a-post-causes-comments-to-be-disabled?replies=2#post-12260

So here's an annoying bug. When I edit a post via the WordPress for iOS app and save the changes, people are unable to leave comments on the post. However, when I login to the desktop version of the WordPress backend, it tells me comments are allowed. So I uncheck the box, save the post, then check the box, save the post and comments are enabled again.

So after diagnosing the problem with a hunch that it could be Edit Flow screwing things up, it looks like it's the culprit. With Edit Flow disabled, I can't replicate the problem using the steps in the post. With Edit Flow enabled, I can replicate the problem every time.

This is version 0.8 I'm using of Edit Flow, the latest version.

**Comment by cojennin** [comment]
Tried recreating this using the store build of WordPress for iOS (v6.1) and Edit Flow v0.8.1 on my local development site but wasn't able to reproduce.

Steps to reproduce:
1. Created a post in WordPress and published it
2. Edited the post and added some text to the post body
3. Posted a comment to post as an anonymous user (not logged in)
4. Comment was successfully added to the post

Are you still encountering this issue? If so, any steps I'm missing? 

(note: I'm using the default WordPress comments system)

**Comment by cojennin** [comment]
Just checking in to see if you're still encountering this issue with the latest version of Edit Flow and iOS for WordPress. Tried a few more attempts at reproducing it but have yet to encounter the issue.

**Comment by TheJeffr0** [comment]
Hey there. Sorry for the lengthy delay in response. I currently can't test to see if it's been fixed because I'm experiencing a different issue with the app where it doesn't load published posts. The app thinks the site doesn't have any posts. Once I get that figured out, I'll confirm if the edit flow bug is fixed.

**Comment by TheJeffr0** [comment]
Ok, I can confirm that the issue still exists. 

I opened the WordPress for iOS mobile app and edited a published post.
I viewed the post in a desktop browser and the comment section was closed.
I clicked the Edit Post link and the Discussion meta box has comments checked. 
To turn comments back on for the post, I have save the post in the desktop browser from the WordPress backend.

**Comment by TheJeffr0** [comment]
If you'd like to see what happens in real time, I can do a screenshare Google Hangout with you.

**Comment by cojennin** [comment]
@TheJeffr0 sure, let me just double check those steps on my setup. 

Also, what other plugins do you have enabled on your site? Might help with trying to recreate the issue on my setup.

**Comment by cojennin** [comment]
@TheJeffr0 definitely following those steps and haven't managed to trigger it on my environment using the iOS app yet

Would be interesting to see it live, but also curious what plugins (and theme) you're running alongside Edit Flow. Would be helpful in trying to recreate this issue.

**Comment by TheJeffr0** [comment]
Here is the list of active plugins on the Tavern.

ACTIVE PLUGINS:

Add From Server: 3.3.1
Akismet: 3.1.11
AMP: 0.3.2
Author Avatars List: 1.9.6
Basic Comment Quicktags: 3.3.1
Better Extended Live Archives: 1.5
Blubrry PowerPress: 7.0
Crowd Control by Postmatic: 1.1
Edit Flow: 0.8.1
Elevated Comments: 1.1.3
Epoch: 1.0.14
FV Gravatar Cache: 0.3.6
Instant Featured Image: 1.0.1
Jetpack by WordPress.com: 4.0.3
No Self Pings: 0.2
Postmatic & Postmatic Labs: 2.0.3
Post Template: 3.4.5
Post Title Spell Check: 1.0.4
Press This New Post: 1.0
Public Post Preview: 2.5.0
Publish Confirmation: 1.0
Pull Quotes: 1.0.1
RS System Diagnostic: 1.0.1
Sharpen Resized Images: 2.0
Show Parent Comment: 0.2.1
Simple Comment Editing: 1.9.4
Simple Google Analytics: 2.2.2
Simple Trackback Validation: 2.1
Swiftype Search: 1.1.47
SyntaxHighlighter Evolved: 3.2.1
Telegram Sharing Button for Jetpack: 1.1.1
TW Recent Posts Widget: 1.0.5
VaultPress: 1.8.3
Wapuuvatar: 2.5
WhatsApp Sharing Button for Jetpack: 1.3.1
WordPress Beta Tester: 1.0.1
WP-Polls: 2.73
WP Migrate DB: 0.8
WP Recent Comments With Avatars: 1.0
WP Rollback: 1.3

**Comment by TheJeffr0** [comment]
Our active theme is WordPress Tavern Theme 0.1.2 which is a child theme based on Justin Tadlock's Stargazer.

**Comment by TheJeffr0** [comment]
I updated Edit Flow on our site to 0.8.2 and tried to replicate the problem and it seems to be fixed. There is one instance during testing where editing and then saving the changes of a post in the WordPress for iOS mobile app caused it to be republished. I tried to replicate this issue as well and after a half hour of testing, was not able to.

**Comment by cojennin** [comment]
Fantastic! Not sure what changed that caused the fix, but I'll take it. If I can get my hands on another iPhone to test again I'll give it a whirl to see if I can recreate the republished issue

**Comment by kraftbj** [comment]
I'll mark this as closed. If it comes up again, drop a comment and we'll reopen. Cheers!
