### ISSUE TITLE
Indicate who was notified when an editorial comment (or other notification) is sent

### ISSUE THREAD

**Issue by jerclarke** [Automattic/Edit-Flow#270]
A big issue our users are having is that after they submit an editorial comment they don't remember if they subscribed a user/group in Notifications before or after the comment. 

It would be nice if there was some indication after submitting a comment as to who was notified. If they saw a message like "No one was notified" it would remind them to add their editor in Notifications and add a new comment/re-edit the status. If they saw "Sub-Editors Group notified" then they could rest easy. 

Ultimately the same goes for status changes (a message at the top below "post saved") and everything else. Users would get peace of mind knowing the notifications were sent and eventually would learn to miss the messages when they had failed to subscribe the appropriate person. 

Any leads on the most efficient way to build this as a plugin are very welcome.

**Comment by sboisvert** [comment]
@WPprodigy I think this could be a good issue to work on. Do you want to test it and see if it works as intended and work with @jerclarke and @goodguyry on if it fits the plugins workflow?

**Comment by WPprodigy** [comment]
Hey @goodguyry,

Thanks for the PRs, nice work! Just checking in to see if you think you’ll have some time to work on this in the near future? Happy to help assist with this further. If you don’t think you’ll be able to get around to this soon, just let me know and I can take over the PRs from here if you would like.

**Comment by jerclarke** [comment]
FWIW: This ticket is pretty much done, as the main change is already merged to `master`. 

If someone can merge my change to the email template in #479 (as described in #478) then this feature will be really really finished (since I think they are related). Both could probably go into `0.8.3` together if there's still will to do that release before moving to `0.9`.

**Comment by jerclarke** [comment]
Closing this because it's already been merged, and remaining fixes/improvements (e.g. #483 ) are something else.
