### ISSUE TITLE
Check box custom field - default to checked

### ISSUE THREAD

**Issue by jiunchin** [Automattic/Edit-Flow#276]
On load of a new custom post, I like to be able to default the check box custom field to "checked".  Currently I use java script but find it not as reliable and from time to time causes issues and conflict with other plugin.  It would be great if we can build an option to default this.

**Comment by cojennin** [comment]
Have you tried using `add_post_meta` with `unique` set to `true` when you create a post? Should be able to use it to set a default value.

**Comment by cojennin** [comment]
Have discussed defaulting to checked in #298. Would be interested to hear other folks use cases on defaulting to checked! Often it seems like a new editorial metadata could be created with the understanding from user's that unchecked is default, but would be great to hear folks make a case for default values (especially default values outside of "checked"). Recommending close, but feel free to way in or create a new issue!

**Comment by cojennin** [comment]
Haven't heard any more input from folks on this issue. Responded with some thoughts on #298, feel free to check them out there. Going to close this, but if folks would like to provide more input on it feel free to open up a new issue or [post](https://wordpress.org/support/plugin/edit-flow). Thanks!
