### ISSUE TITLE
Archived post status reverts URL to 'preview' status

### ISSUE THREAD

**Issue by patrickbjohnson** [Automattic/Edit-Flow#280]
Running into a small cosmetic issue but wondering if there is a fix for it. 

Currently using the EditFlow plugin to manage old posts without our CMS. Strictly just using the archive mechanism to hide custom posts from a users view on the home page and throughout our site. 

On an individual custom post, I need to display links to archived posts (its an events site so we need to link to old events pages). 

All works fine with the exception of the link that is generated with the archived pages. In a published state, the url is as follows: ``` http://localhost:8888/ENKwp/shows/jens-show/ ``` and when I archive a post, the URL changes to this : ```http://localhost:8888/ENKwp/?p=619&post_type=enk_show&preview_id=619```

Any particular reason for this? And is there a way to maintain the original, clean URL?

**Comment by cojennin** [comment]
Following up, are you still encountering this issue?

**Comment by cojennin** [comment]
Following up one more time, any updates you can provide?

**Comment by cojennin** [comment]
Unable to recreate this issue and have not had reporter feedback for more than a year. Recommending to close.

**Comment by cojennin** [comment]
Closing. Feel free to reopen or create a new ticket if you encounter this issue again and can provide more information!

**Comment by evgeniyefimchenko** [comment]
Hello. We have the same problem.
Created a new status "in the archive" and the pages disappeared from the site issue. I change the property in the theme file function.php
`function make_archived_status_public()
	{
	  global $wp_post_statuses;
	  $wp_post_statuses['v-arhive']->public = true;
	}
add_action( 'init', 'make_archived_status_public');`
After this, the posts became visible, but all their links changed their appearance.
Must be `https://allbriz.ru/gelendzhik/hotel/otel-valensiya/`
It became after the change of status `https://allbriz.ru/?p=34611&post_type=object&preview_id=34611`
How can this problem be solved?
