### ISSUE TITLE
Edit Flow conflicts with Buddypress

### ISSUE THREAD

**Issue by ghost** [Automattic/Edit-Flow#282]
Hello!

I'm currently experiencing an odd issue. I've been using Edit Flow for a long time, and it works perfectly - it has become absolutely vital to our magazine. I've been working on expanding the website however and part of that was installing BuddyPress. However, there's a conflict between Edit Flow and Buddypress that's quite odd, and I was hoping you could, perhaps, help me.

The issue is most notable in the custom statuses, when both plugins are activated. When I open a post, behind status, there is no drop-down menu, no edit button, simply nothing. I cannot change the status of a post. In the post overview, where before at the top of the overview I could filter posts by custom status, now it just offers me "All", "Published" and "Trashed", the custom statuses have disappeared (as well as in the overview itself). However, even "Draft" and "Pending" have disappeared - it's like *all* post statuses have just disappeared. Oddly enough, it still displays all the post statuses in the Unpublished Content widget on the Dashboard, but when I click on any of the custom ones, it just sends me to the all posts overview and they're not filtered. 

Furthermore, I use the "view own posts only" plugin to allow our authors only to see their own posts, but Editors can still see others' posts that are assigned to them to edit - this worked perfectly before. Now, though, when Buddypress is activated, they cannot find the posts by others they've been assigned.

I hope you can help me out. If this is a problem caused by Buddypress... I'll go and ask them but I thought I'd ask here first since I found another Edit Flow/Buddypress error logged here (which was different than my problem as I don't use BBPress, but oh well).

Wordpress version: 4.0
Buddypress version: 2.1.1
Edit Flow version: 0.8

Thank you!

**Comment by cojennin** [comment]
Hrm, not able to recreate this issue. Set up with the following:
WordPress v4.5.2
Edit Flow v0.8.1
Buddy Press v2.5.2
View own posts and media library items only v1.3

When I have all the plugins activated the drop down menu lets me select a custom status for the post and I'm able to filter post's by a custom status. Are you still encountering the issue?

**Comment by cojennin** [comment]
Haven't heard back from reporter and have not been able to recreate this issue, recommending close.

**Comment by cojennin** [comment]
Going to close. Report is over 2 years old and have not heard back from original reporter. Feel free to reopen or create a new issue if you have new details to provide. Thanks!
