### ISSUE TITLE
Custom post type previews are broken

### ISSUE THREAD

**Issue by chrisvanpatten** [Automattic/Edit-Flow#285]
When I have Edit Flow activated, I get a 404 error when I try to preview a single CPT post draft.

I don't have EF custom statuses or EF notifications enabled for this custom post type.

The post type is set to 'public' as well.

Any ideas for debugging this?

**Comment by cojennin** [comment]
Hrm, not seeing the issue when using WP 4.5 and Edit Flow 0.8.1. Is this still an issue for you?

**Comment by cojennin** [comment]
Haven't been able to recreate this and haven't had reporter feedback for more than a year. Suggesting for close

**Comment by cojennin** [comment]
Closing. Feel free to reopen or create a new ticket if you encounter this issue again and can provide more information!
