### ISSUE TITLE
Calendar has duplicate days: November 2nd occurs twice, scheduled posts appear for both days

### ISSUE THREAD

**Issue by ieatbugs** [Automattic/Edit-Flow#286]
The date of November 2nd occurs twice on the calendar - posts that are scheduled for this day display on both instances of November 2nd in the calendar.

**Comment by cojennin** [comment]
I am also not able to reproduce the issue. Do you have more details?

**Comment by cojennin** [comment]
Not able to reproduce and have not had any further feedback, suggesting close.

**Comment by cojennin** [comment]
Closing. Feel free to reopen or create a new ticket if you encounter this issue again and can provide more information!
