### ISSUE TITLE
Missing some escaping

### ISSUE THREAD

**Issue by vaurdan** [Automattic/Edit-Flow#288]
The whole plugin code should be reviewed to add late escaping. There are some missing escaping that really needs to be addressed.

**Comment by cojennin** [comment]
Do you have some specific examples of code? Would be great to break this into a few issues to be tackled by folks looking to contribute.

**Comment by cojennin** [comment]
Going to recommend closing this. Would be great to open new issues on specific areas in the Edit Flow code where escaping is needed!

**Comment by cojennin** [comment]
Going to close. Would be great to get a few tickets highlighting areas in the code where escaping is needed!
