### ISSUE TITLE
Previewing posts causes 404 on URL without trailing backslash.

### ISSUE THREAD

**Issue by matthewmcvickar** [Automattic/Edit-Flow#293]
**Problem:** Custom post statuses are breaking post preview links—they require a trailing slash to work when Edit Flow is enabled.

**Details:** When a post (the default Post type) has a status of Draft or any of Edit Flow's custom post statuses, preview URLs do not work unless they are changed manually. This 404s: http://example.com?p=1234&preview=true, but if we add a trailing slash, it works: http://example.com/?p=1234&preview=true

1. Disabling the Edit Flow plugin stops this behavior.
2. If custom post statuses are disabled for posts, the preview links work.

Any ideas?

**Comment by cojennin** [comment]
Hrm. Is this still an issue with WP 4.5? Using WP 4.5, when I preview a link a trailing slash is automatically appended so not seeing any 404's.

**Comment by matthewmcvickar** [comment]
This ended up being a CDN issue; I'm sorry for not following up. Thank you!

**Comment by cojennin** [comment]
No worries, thanks for following up!
