### ISSUE TITLE
Calendar module's JS interferes with another plugin that uses an .editing class

### ISSUE THREAD

**Issue by daveross** [Automattic/Edit-Flow#295]
reset_editorial_metadata() is hiding elements from another plugin we're using. The selector $('.editing') is overly-broad. I'll submit a PR to narrow the focus to just look at the Calendar page, but you may want to address this closer to where the click handler is defined instead.

**Comment by philipjohn** [comment]
Closing in favour of 351 which covers the issue in a little more detail.
