### ISSUE TITLE
is this plugin discontinued?

### ISSUE THREAD

**Issue by shawaj** [Automattic/Edit-Flow#306]
Has development on this plugin stopped?

Looks like it is really useful but hasn't been updated in 2 years.

Thanks

**Comment by samglover** [comment]
There's not much going on at the moment, but there are definitely still some people working on this plugin. My hope is that since it's an Automattic project, it will eventually get updated.

**Comment by zkenstein** [comment]
Notification mail never sent/arrived. Anyone has faced this?

**Comment by kraftbj** [comment]
Howdy folks! I'm going to close out this ticket. The plugin is maintained but we're not focusing on adding new features at this time.
