### ISSUE TITLE
PHP Strict Standards:  Only variables should be assigned by reference

### ISSUE THREAD

**Issue by AramZS** [Automattic/Edit-Flow#311]
On activate, the following error occurs:

PHP Strict Standards:  Only variables should be assigned by reference in [...]wp-content/plugins/edit-flow/common/php/class-module.php on line 564, referer: [...]wordpress/wp-admin/update.php?action=install-plugin&plugin=edit-flow&_wpnonce=1ccd691aba

**Comment by cojennin** [comment]
Closing, fixed by #340
