### ISSUE TITLE
$start_date_value within the story_budget_time_range function (story-budget.php) is using none localized php date functions

### ISSUE THREAD

**Issue by rpkoller** [Automattic/Edit-Flow#312]
so the german localization is showing July 24th as date instead of 24. Juli. maybe use the wordpress date_i18n function instead of the php date function? cheers r.

**Comment by cojennin** [comment]
Once the changes from #308 are merged in this should be corrected.

**Comment by TheCrowned** [comment]
#308 was (rejected) and split into two separate PRs. The relevant one is #371, which was merged into production, so this issue can be closed now.
