### ISSUE TITLE
Tiny translation bug

### ISSUE THREAD

**Issue by Warpsmith** [Automattic/Edit-Flow#315]
It has already been mentioned elsewhere that story-budget.php and calendar.php doesn't use WordPress's date_i18n function, which makes translation difficult...

...but this is something else. Line 1342 in calendar.php must be changed from:

echo sprintf( __( 'for %1$s through %2$s'), $first_date, $last_date );

To:

echo sprintf( __( 'for %1$s through %2$s', 'edit-flow'), $first_date, $last_date );

...for the translation to take hold.

**Comment by cojennin** [comment]
Closing, this was fixed by #337
