### ISSUE TITLE
Small proofreading correction

### ISSUE THREAD

**Issue by Warpsmith** [Automattic/Edit-Flow#317]
Sorry, I don't understand how Github works and all tutorials I've found are way over my head, otherwise I would contribute directly to the code. I hope it is all right this way too.

Line 36 in calendar.php. The string have the last word "date" duplicated by mistake:

'extended_description' => __( 'Edit Flow’s calendar lets you see your posts over a customizable date range. Filter by status or click on the post title to see its details. Drag and drop posts between days to change their publication date date.', 'edit-flow' ),

It should be:

'extended_description' => __( 'Edit Flow’s calendar lets you see your posts over a customizable date range. Filter by status or click on the post title to see its details. Drag and drop posts between days to change their publication date.', 'edit-flow' ),

**Comment by kraftbj** [comment]
Thanks!
