### ISSUE TITLE
Is the master branch production ready?

### ISSUE THREAD

**Issue by hedii** [Automattic/Edit-Flow#320]
Hi,
is the master branch of this repo here on github production-ready ?
i can see it has a different version than the version on wordpress plugin repo (0.8 vs 0.8.1).
thanks

PS: if this plugin is not discontinued, i would like to contribute, i see there is a lot of not internationalized text on this plugin, on v0.8.

**Comment by hedii** [comment]
hello?

**Comment by cojennin** [comment]
Howdy! The master branch of Edit Flow isn't always production ready so be careful about using it in production.

Please feel free to open a pull request with contributions to internalization support! Definitely need help with making sure dates are properly supported. Take a look at #312 and #315 if you're looking for a place to start.
