### ISSUE TITLE
notifications.js not loading from local network

### ISSUE THREAD

**Issue by apazga** [Automattic/Edit-Flow#323]
Hi!

We had to disable EditFlow plugin to be able to edit posts and use the dashboard without an "eternal loading state".

If you use the dashboard from company network with EditFlow plugin enabled, this JavaScript never loads but it's expected, causing troubles with the Edit Post functionality.
https://--my-blog-url--/wp-content/plugins/edit-flow/modules/notifications/lib/notifications.js?ver=0.8

If you access from outside company network, there is no problem at all, and everything is ok.

Hope it helps!

WP version: 4.3.1 (but same behaviour in previous versions)

**Comment by cojennin** [comment]
Strange, it was only notifications.js that was causing problems? None of the other js files Edit Flow loads into the admin we're causing issues?

**Comment by cojennin** [comment]
Any updates to this issue?

**Comment by cojennin** [comment]
Think it might be tough to recreate this issue since it's isolated to a company network. Will suggest we close, but will remove label if more info is added to ticket

**Comment by cojennin** [comment]
Going to close, feel free to reopen with any new developments!
