### ISSUE TITLE
Custom statuses are not installed if tags exist already?

### ISSUE THREAD

**Issue by DrLightman** [Automattic/Edit-Flow#324]
I've installed the public 0.8 plugin and in some websites I couldn't see all the five predefined custom statuses:

pitch
assigned
in-progress
draft
pending

Checked the code and found this in \edit-flow\modules\custom-status\custom-status.php line 166:

```php
		// Okay, now add the default statuses to the db if they don't already exist 
		foreach( $default_terms as $term ) {
			if( !term_exists( $term['term'] ) )
				$this->add_custom_status( $term['term'], $term['args'] );
		}
```

But what if they already exist?

**Comment by DrLightman** [comment]
The test is made on the term name, not slug. (localized)

**Comment by DrLightman** [comment]
Also, there need to be a function to completley wipe all Edit-Data from a WP installation. I'm having an hard time to let the plugin reinstall module data.

**Comment by cojennin** [comment]
> Maybe you had to use a taxonomy for these.

Yea, think we should be scoping [the call to `term_exists`](https://github.com/Automattic/Edit-Flow/blob/master/modules/custom-status/custom-status.php#L169) by passing the optional taxonomy parameter. Will work on a fix and test it.

> Also, there need to be a function to completley wipe all Edit-Flow from a WP installation. I'm having an hard time to let the plugin reinstall module data as if it were the first time.

Yea, would be good to investigate the tear down procedures for Edit Flow when it's uninstalled. Should open that as a separate issue.

**Comment by cojennin** [comment]
Hrm, looking at this again, seems like the term_exists check is in place for [the reason highlighted in this comment](https://github.com/Automattic/Edit-Flow/blob/master/modules/custom-status/custom-status.php#L769). 

Could be an odd looking slug is created if the term already exists (even if under a different taxonomy). Will look into it.

**Comment by cojennin** [comment]
Going to close this. Will work on documenting this behavior (and the reason for it).
