### ISSUE TITLE
Extra "Posts" Export Option

### ISSUE THREAD

**Issue by jordansaniuk** [Automattic/Edit-Flow#326]
When the Edit Flow plugin is activated, a second "Posts" option becomes available in Tools > Export. It appears to export something called dashboard-note but doesn't produce any content when downloaded. 

![screen shot 2016-02-19 at 4 34 26 am](https://cloud.githubusercontent.com/assets/11172864/13171695/30af80c4-d6c2-11e5-9732-1ce8f0783293.jpg)

**Comment by cojennin** [comment]
@jordansaniuk this should be fixed by #341. Do you have a few minutes to review?

**Comment by cojennin** [comment]
Closing this since #341 was merged
