### ISSUE TITLE
Willing to help continue development on Edit Flow

### ISSUE THREAD

**Issue by stevejburge** [Automattic/Edit-Flow#332]
Hi all

There's been some discussion this week about the way forward for EditFlow:
http://wptavern.com/hey-automattic-whats-going-on-with-edit-flow

We're heavy users of Edit Flow and would love to see it updated and improved. To that end, we're willing to help with development resources.

Over the last few years we've successfully forked / taken over several CMS plugins. Sometimes the original developers approached us as a partner or safe pair of hands. Sometimes the software was abandoned. But, we know what we're doing. In fact, we're doing it twice more in the next few weeks. 

So, please consider this a conversation starter. We're happy to help if needed.

**Comment by sillybean** [comment]
I would also be happy to contribute.

**Comment by KuneStudio** [comment]
Hi !
I've started to fork the plugin. I'm going to check the issues that you have the most and that are the most blocking. 
First I need to fill the plugin with demo data, and it's probably going to take some time.
Hope to release some bugfix soon. 
Remember that I'm doing it on my free time :) So please, be indulgent.

**Comment by cojennin** [comment]
It's great to see folks are still interested in the livelihood of this plugin!

I understand the desire to fork Edit Flow given the support for it has been lackluster. But before you do I'd encourage folks to help contribute to this repository, if only to demonstrate a sustained interest and willingness to contribute (something that might you give more cred when forking).

Some thoughts on how to contribute:

1. Help with triaging [open issues](https://github.com/Automattic/Edit-Flow/issues). Are all open issues still relevant today? Are there open issues that need more information? Have we captured all the issues on the [.org plugin page](https://wordpress.org/support/plugin/edit-flow) in Github?
2. Help with triaging [open pull requests](https://github.com/Automattic/Edit-Flow/pulls). Is the pull request still relevant? It could be the case that [one pull request](https://github.com/Automattic/Edit-Flow/pull/307) has already fixed the issue of [another pull request](https://github.com/Automattic/Edit-Flow/pull/278). It might be the case that a pull request needs to be updated to support more recent functionality or changes in WordPress. Has the [author of the pull request been contacted](https://github.com/Automattic/Edit-Flow/pull/316#issuecomment-212225954) to see if they'd be willing to undertake this work?
3. [Help write tests!](https://github.com/Automattic/Edit-Flow/blob/master/tests/test-edit-flow-starter.php#L7).
4. Write a pull request of your own! Hopefully one that fixes an outstanding issue or improves existing functionality.

The more folks can do to take an active interest in Edit Flow the more likely it is that more attention will be given to Edit Flow from Automattic or other community members like yourself!

I'm happy to work with anyone on any of the above steps (or any steps you can think of!). Please feel free to reach out over email or on Github!

**Comment by cojennin** [comment]
Just following up to see if anyone has other thoughts? If folks are interested in contributing and looking for ways to help, let me know! There's plenty to do and I'd be happy to help!

**Comment by cojennin** [comment]
Alrighty, going to close this. If anyone's interested in helping out with maintaining Edit Flow please see my above comment on ways to contribute! Would be great to have folks on board interested in lending a hand!
