### ISSUE TITLE
Custom post status - Scheduled cant be saved if modded

### ISSUE THREAD

**Issue by gabu69** [Automattic/Edit-Flow#333]
Im using edit flow only for custom status and theres a big bug I noticed:

When an user doesnt have user capabilities of publish_posts and an author/editor/admin schedules his post, he wont be able to save any mod while its in schedule mode. If he has capabilities of edit_published_posts he will be able to edit it after its published, but it will never have an option while its on scheduled

https://wordpress.org/plugins/edit-flow/

**Comment by cojennin** [comment]
Doesn't look like it's Edit Flow causing this issue. Appears to be [a change in WordPress version 4.4](https://core.trac.wordpress.org/ticket/33694) made it so contributors could no longer edit scheduled posts.

**Comment by ewelin34** [comment]
Ok, I am an admin on our site, but yet I can no longer schedule posts since putting in some custom status. Suggestions?

**Comment by cojennin** [comment]
What happens when you try to schedule a post when you have a custom status? Do you get an error of some kind?

**Comment by cojennin** [comment]
@ewelin34 any updates on this issue?

**Comment by cojennin** [comment]
@gabu69's issue appears to be core WP functionality as of WP 4.4. Not sure what @ewelin34's issue is, but think it may be related to #301? Closing this in favor that issue, which should be fixed as of #350
