### ISSUE TITLE
Suggestion: Implement git-flow on this repo

### ISSUE THREAD

**Issue by robertsky** [Automattic/Edit-Flow#339]
If it is possible, can we implement git-flow on this repo? http://nvie.com/posts/a-successful-git-branching-model/

In this manner:
- The master branch will only consist of the released versions, which are tagged as well. In a sense, the master branch here is the trunk/stable branch on WordPress svn.
- The develop branch is where we do the heavy lifting. Ideally, it should consist of only merged PRs from:
- Hotfix/features branches. This is where the actual work are done. Hotfix branches contains patches for bugs while the feature branches are new or improved features to be worked on.
- A release branch can be branched off from the develop branch closer to the release date of each version. If there are any patches to be done, hotfix branches can be used and then apply equally on both develop and release branches. The release branch can also be used for the development branch on WordPress svn.

Hotfix and feature branches are superfluous here, in my opinion, since most of us are contributing by forking and submitting pull requests. Just need to label the branches proper, and that may do.

I am more concerned with master and release branches here as this will aid in pushing out new translatable strings to GlotPress (as I had mentioned in #335) and as well as giving the site administrators an option to test a beta release (release branch) and feed back to the team here that there are issues, if any, before the stable version is pushed out.

**Comment by cojennin** [comment]
Definitely an interesting idea. A couple of thoughts:

- The more structure added to a workflow the more difficult it can be for contributors to adopt. Folks familiar with git and Github projects are often most familiar with making PR's against a master branch, having them reviewed and merged.
- With structure comes bookkeeping. Can definitely payoff (you mentioned one area, making sure a release is ready for GlotPress). But it also means more time that needs to be invested in maintaining this bookkeeping by folks running the repo
- I'd like to either 1) see a few more active contributors working on the plugin before trying to introduce a new git workflow. That way there's more folks to help with maintenance and on-boarding of new contributors 2) see what issues arise with trying to keep this Github repo in-sync with SVN and GlotPress. If it's really problematic, would be open to moving to this workflow sooner

**Comment by mjangda** [comment]
This project did use git-flow in the early days; there were many issues with it (which @cojennin noted).

**Comment by cojennin** [comment]
@robertsky did you have any further thoughts you wanted to add? Going to punt on using git-flow for the moment, but wanted to make sure you had a chance to respond. You made some interesting points and if we reopen this down the road I want to make sure we collected them all.

**Comment by cojennin** [comment]
@robertsky going to close this for the time being. As I mentioned above, we can revisit this idea if we find the current Git workflow unsuitable. Thanks for input!
