### ISSUE TITLE
Deprecated function Notice in Back end

### ISSUE THREAD

**Issue by jghazally** [Automattic/Edit-Flow#355]
Noticed this today when upgrading plugins and wordpress. Logged into the backend after using wp-cli to upgrade plugins and wp. 
`
Notice: get_currentuserinfo is <strong>deprecated</strong> since version 4.5! Use wp_get_current_user() instead. in ..../wp/wp-includes/functions.php on line 3658
`

**Comment by cojennin** [comment]
Thanks for logging that issue! This will be fixed with the next release of Edit Flow (fixed by #334).
