### ISSUE TITLE
Update styles on settings page 

### ISSUE THREAD

**Issue by cojennin** [Automattic/Edit-Flow#361]
The Edit Flow settings page could use some style updates so it doesn't look as funky on smaller screen sizes. See below screenshot for example.

![screen shot 2016-08-31 at 3 25 52 pm](https://cloud.githubusercontent.com/assets/1888152/18143249/3f248670-6f8f-11e6-9c2b-c86581b91f5c.png)

**Comment by WPprodigy** [comment]
The above PR is merged and looks good in my testing 😀

Closing out this issue, thanks @TheCrowned
