### ISSUE TITLE
Feature Request - CSV group upload

### ISSUE THREAD

**Issue by OllieCo** [Automattic/Edit-Flow#369]
Hi Team, I love the plugin and was wondering if there are any plans to allow for editorial group creations using a CSV upload or something similar? I work for a University. Students are expected to contribute to each others' posts. Some classes have hundreds of students that work in groups. It would be really good if we could organise them into groups via a spreadsheet, and import it into the groups function. 

Thoughts?

Cheers,
Ollie.
(sorry if this was posted in the wrong place).

**Comment by cojennin** [comment]
Reposting this response [from the forum](https://wordpress.org/support/topic/function-request-group-csv-upload/)

> An interesting idea, but not one we've got in the pipeline. Automating user group management for large organizations seems like a better fit when built as a separate plugin or WP CLI command that works with Edit Flow. There might be some folks on Github who have already done that work and could assist you. If not, you could roll your own plugin or WP CLI command (or have someone to do it for you).

**Comment by cojennin** [comment]
Going to close this out. Response [is in the forum!](https://wordpress.org/support/topic/function-request-group-csv-upload/)
