### ISSUE TITLE
Bug Fix: properties that may not exist are attempted to be accessed

### ISSUE THREAD

**Issue by jvolfson** [Automattic/Edit-Flow#383]
In the dashboard, if the $post_count object has no results for a custom status (for instance, if you create a status called 'in progress', but have not yet assigned that status to a post), line 166 will generate an error:

Notice: Undefined property: stdClass::$in-progress in /var/www/html/web/app/plugins/edit-flow/modules/dashboard/dashboard.php on line 166

Added a check to see if the object has the property before attempting to use it.

https://github.com/Automattic/Edit-Flow/pull/382

**Comment by raduconst** [comment]
I checked this and it seems that it's not a problem anymore. 

Every status has a slug and it will appear for sure in the $post_count object. This means that this line: 
$post_count->$slug
will have for sure a value (whether it's 0 or a string with the number of posts). I tried to replicate this or think of a situation when this problem appears but I couldn't replicate it.

@jvolfson Can you confirm that this is still happening or maybe give me some more details about how I can replicate this, please?

**Comment by sboisvert** [comment]
Closing the issue. @jvolfson if you have any more information feel free to add it here.
