### ISSUE TITLE
Cannot load calendar for all roles except Admin

### ISSUE THREAD

**Issue by RhaeY** [Automattic/Edit-Flow#384]
Everything was working fine but suddenly calendar for editor, contributor and author stop working. It shows cannot load calendar. Same issue with Story Budget.  
It is working fine for User having Admin role.  If i assign manage_option capability to other roles then calendar is visible to them but i don't want to give them this capability. I am a starter in wordpress and any help would be much appreciated. 

Edit : It's an emergency kind of situation for me. If anyone knows the fix please please do tell. I'm not a wordpress developer.

**Comment by philipjohn** [comment]
Hi! I'm not seeing this issue anywhere else, so I suspect a change in your site has caused the situation. Perhaps something changed the user capabilities recently? Best thing to do is the old trick of disabling other plugins and seeing if the issue goes away.
