### ISSUE TITLE
Integrate the Plugin "Advanced Custom Fields"

### ISSUE THREAD

**Issue by michaelscheurer** [Automattic/Edit-Flow#385]
Hi. 
I would like to present an idea to you to improve Edit Flow even more. What do you think about? I would be curious.

One of the most useful functions in Edit Flow are the [custom statuses](http://editflow.org/features/custom-statuses/)

What if we would integrate instead of Editorial Metadata one of the most powerful plugins [Advanced Custom Fields](https://srd.wordpress.org/plugins/advanced-custom-fields/)?

The main idea is: When a custom field is added to posts, you can then decide on Edit flow, if this certain field will be displayed or not (like now on Editorial Metadata). 

Why doing the work for the Editorial Metadata again, if he's already done?

**Comment by michaelscheurer** [comment]
Ok. I did it myself. You'll find the corresponding pull request on this repo.

**Comment by philipjohn** [comment]
#387

**Comment by WPprodigy** [comment]
Closing this out.

We could/should certainly add hooks to the calendar markup though to allow for such customizations externally. If there aren't enough hooks for you to use to achieve this currently, a PR for that would be the best option here.
