### ISSUE TITLE
Feature Request: Integrate with Basecamp To-Dos

### ISSUE THREAD

**Issue by courane01** [Automattic/Edit-Flow#388]
I'd love to integrate with Basecamp to-do's. I'd be thrilled to test, but I"m not much of a coder.

**Comment by sboisvert** [comment]
Hi @courane01! 

I think this is a great idea but not necessarily something that should be part of the core edit-flow plugin. By that I mean that if someone were to want to build an adapter we could have a link to it inside the plugin but I don't think we'd necessarily include it for everyone.

Thanks for the suggestion!

**Comment by WPprodigy** [comment]
Agree that this is a better fit for a custom module, rather than being included in the plugin itself.

Linking to https://github.com/Automattic/Edit-Flow/issues/462 as an example for where this extendability could be used.
