### ISSUE TITLE
As of WP 4.8, `value="1"` is now visually indicating a checked box on `<input type="checkbox"`

### ISSUE THREAD

**Issue by lacymorrow** [Automattic/Edit-Flow#397]
After updating to WP4.8, checkboxes started defaulting to a checked visual state when they previously had not. 

It seems that this is related to the inclusion of :
`value="1"`

on line #415 of https://github.com/Automattic/Edit-Flow/blob/master/modules/editorial-metadata/editorial-metadata.php#L415

Using `value="true"` doesn't cause this issue but I'm unsure if there are any other consequences of that change.

Chrome Latest on OSX but client reports were coming from various machines.

**Comment by philipjohn** [comment]
Thanks for the report @lacymorrow !

Could you provide some more detail about where you're seeing this within the interface and some reproduceable steps that show a different behaviour in 4.7 vs 4.8 please?

**Comment by lacymorrow** [comment]
There is an `input type=checkbox` with selector `#_ef_editorial_meta_checkbox_needs-photo`. It has the hardcoded property `value=1`. 

In WP4.7 this checkbox shows unchecked. Upgrade to 4.8 and it is checked by default. 
There may be an underlying WP core bug for this issue.

**Comment by justnorris** [comment]
Hey @lacymorrow - I was about to tackle the problem but I don't see it here. The checkbox is unchecked by default for me in WordPress 4.9.2.

If the problem is still present, can you please describe how to reproduce it?

**Comment by lacymorrow** [comment]
Closing as new versions of WP seem to have fixed the issue and I am unable to reproduce using 4.9.X
