### ISSUE TITLE
Allow editors full access to just this plugin.

### ISSUE THREAD

**Issue by PogHallam** [Automattic/Edit-Flow#398]
We have a need for users with role "editor" to have full access to this plugin - i.e. the same as an admin.

Is this currently possible, either with custom code or a plugin? Any help very much appreciated!

Thanks,
Oliver

**Comment by philipjohn** [comment]
Hi! Yep, you should be able to filter core's capabilities code in the right places to allow access. It could be tricky, so let me know if you have issues.
