### ISSUE TITLE
Allow non-post type data to be injected into the calendar view

### ISSUE THREAD

**Issue by cklosowski** [Automattic/Edit-Flow#417]
I've been asked by a user of Post Promoter Pro to see if I can support adding social media shares to the Edit Flow calendar. After inspection it looks like all the data is very heavily relying on the `WP_Post` objects.

For integrations it would be ideal to allow a way to inject some data into the views. I have a little work in progress to get this going, and some sample code that seems to work.

Will submit a PR for the initial thought and hopefully can work forward to maybe get it merged in as a feature.

**Comment by WPprodigy** [comment]
Closing this issue, the PR has been merged. Thanks @cklosowski
