### ISSUE TITLE
Add PHPCS standard to the plugin

### ISSUE THREAD

**Issue by david-binda** [Automattic/Edit-Flow#440]
As we want to be good citizens, we should fully embrace the WordPress coding standards in terms of this plugin. And, as the plugin is being used on the WordPress.com VIP platforms, we also should be stricter than the standard WordPress coding standards, and fully embrace the VIP and WordPressVIPMinimum standards.

examining the way `wp scaffold plugin my-plugin` ([#](https://developer.wordpress.org/cli/commands/scaffold/plugin-tests/)) generated the PHPCS standards and incorporates it into Travis configuration should give us some starting point for making this true.

Some other related reading:

* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
* https://github.com/Automattic/VIP-Coding-Standards

**Comment by cojennin** [comment]
Added with #559
