### ISSUE TITLE
Custom post statuses added via filter are not added to status column

### ISSUE THREAD

**Issue by pdewouters** [Automattic/Edit-Flow#445]
If I add a custom post status via `display_post_states`, it is not added to the custom status column, even though it is appended to the post title ( but hidden )

**Comment by justnorris** [comment]
Hi Paul,
Thanks for reporting the issue. I was able to reproduce the bug. Marking the issue as a bug that should be resolved sooner rather than later. This affects also Edit Flow compatibility with plugins like Liveblog and Gutenberg.

**Comment by mikeyarce** [comment]
@pdewouters I've got a PR which should fix the issue of Post States note displaying, can you give it a try and let me know if it works for you?
PR: https://github.com/Automattic/Edit-Flow/pull/446

**Comment by sboisvert** [comment]
fixed in #446
