### ISSUE TITLE
Bug: Filters always stay at the last filtered status

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/Edit-Flow#447]
In the Story Budget and Calendar modules, there are filters at the top you can use to retrieve certain posts into view.   If you use a filter, leave the page, and come back, the last filter used will still be there.

Steps to reproduce:
1. Go to the Calendar
2. Pick a category
3. Click "Filter"
4. Leave that page
5. Come back to the Calendar
Result:  You will still have the same category filtering.

Solution:  We should reset the filter when someone comes back to the page instead of loading whatever the previous filter was.

**Comment by TheCrowned** [comment]
I was looking into this, and found that the _filter memory_ is not a bug, but a feature. There are several functions in the relevant php files to allow this to happen, by saving filters status in the database a usermeta. So I guess the answer is then: is this behavior fine, or is it bad?

**Comment by mikeyarce** [comment]
Interesting!  I'm not a "real" use of Edit-Flow so I wonder if maybe asking some folks who use this regularly might be useful?   From my brief time using it, I wasn't aware that the filters would persist and it felt odd since other Filters in WordPress don't have that same behaviour.

**Comment by WPprodigy** [comment]
I'd be super hesitant to remove "a feature" like this. Could be an important piece of some workflows.

I think we should leave this for now, but could certainly revisit. Perhaps when/if the UI is cleaned up.
