### ISSUE TITLE
Gutenberg: Custom Post Statuses not working

### ISSUE THREAD

**Issue by raduconst** [Automattic/Edit-Flow#454]
When creating a new post using Gutenberg, the post status cannot be set and this makes the _custom post statuses_ unavailable. This might be related to https://github.com/WordPress/gutenberg/issues/3144

**Comment by jmarx** [comment]
@mjangda Is there any update on this?

**Comment by bengreeley** [comment]
Any plans on updating Edit Flow to work with Gutenberg (specifically custom post statuses)? It would be a shame if this plugin is no longer going to be supported through the new editor experience given its wide adoption over the years.

**Comment by benlk** [comment]
As I understand it, Edit Flow needs Gutenberg to implement custom post statuses, which is under discussion at https://github.com/WordPress/gutenberg/issues/3144

**Comment by mjangda** [comment]
Sorry for the lack of follow up here.

We're looking into a short-term fix to get custom statuses working with the
5.0 Block Editor.

We'll also follow up on the custom status discussion in Gutenberg as noted
by Ben (thanks for that!)

**Comment by mjangda** [comment]
This was addressed in v0.9.
