### ISSUE TITLE
Dashboard Notepad: note limit, updated time, redirect value.

### ISSUE THREAD

**Issue by mitchelldmiller** [Automattic/Edit-Flow#458]
1) "Updated at" shows published time, instead of last modified time.
Expected behavior: show updated time in widget footer.
Actual behavior: shows published time in widget footer.
Steps to reproduce: save note.

2) Note data is sent as GET. Rejected by Apache when over 8192 bytes on my server.
Expected behavior: update note.
Actual behavior: Apache URL too long.
Steps to reproduce: save big note.

3) Get occasional blank page on submit. Does not check for empty return from [wp_get_referer](https://codex.wordpress.org/Function_Reference/wp_get_referer).
Expected behavior: update note.
Actual behavior: blank page.
Steps to reproduce: save note with Firefox 59.0.2 (64-bit) Mac.
Web server: Apache/2.4.18. PHP 7.0.28. Ubuntu 16.04.4 LTS.

**Comment by rinatkhaziev** [comment]
Both #468 and #469 are merged, closing the issue.
