### ISSUE TITLE
Update for 0.8.3 coming to WP.org?

### ISSUE THREAD

**Issue by ryanboswell** [Automattic/Edit-Flow#475]
While there is a release tagged on Github for `0.8.3` from June 14th, the latest release on the [plugins directory](https://wordpress.org/plugins/edit-flow/) is still at `0.8.2`.

Is there a timeline for when the plugins directory will be updated with the latest release?

**Comment by flagster76** [comment]
Also interested in this version bump, on both the plugins directory and [wpackagist](https://wpackagist.org/search?q=edit-flow)

**Comment by skorasaurus** [comment]
this appears to be no longer valid, 0.9 has been released on wpackagist and plugins directory.

**Comment by mjangda** [comment]
As mentioned by the earlier comment, 0.9 was released.
