### ISSUE TITLE
Editors now viewing all posts

### ISSUE THREAD

**Issue by katsar0v** [Automattic/Edit-Flow#494]
Since I updated to `0.9`, the editors in WordPress do not see the same articles as an administrator. How can I make editors to view all articles from everybody? Thanks!

**Comment by raduconst** [comment]
@katsar0v I have a couple of posts added by the admin and by some editors and both type of accounts can see all the posts from the website. Can you give me some more details about your environment? Are you using any other plugin on your website? What's the WordPress version are you using? All this info would help me replicate the issue and look for a fix.

**Comment by mjangda** [comment]
Going to close this for now. @katsar0v if this issue is still valid, please re-open with more details. Thank you!
