### ISSUE TITLE
notification not working

### ISSUE THREAD

**Issue by iamkingsleyf** [Automattic/Edit-Flow#496]
Hello;

Since the update notification is no longer working.

**Comment by ikawka** [comment]
Also experiencing this issue on v0.9

**Comment by mikeyarce** [comment]
Tested this out today and it seems fine on 0.9.   It might be that the added privilage checks are what might be causing issues.   

If you still have this problem please report back with more details, screenshots, steps to reproduce, and I'd be happy to take a look!

**Comment by iamkingsleyf** [comment]
Except you want a copy of my site with all the plugins in it to test... wordpress email/admin email does not receive notification but contributors do receive.

I only get notified when schedule content is LIVE
