### ISSUE TITLE
PHP7.2 Warning in settings.php due to not Countable object

### ISSUE THREAD

**Issue by NeilWJames** [Automattic/Edit-Flow#498]
Installed the plugin (v0.9) on a PHP 7.2 machine and going to the settings page gives this message:

`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/wordpress/wp-content/plugins/edit-flow/modules/settings/settings.php on line 232`

Code is 
`		if ( !count( $edit_flow->modules ) )`

Seems to work as desired (i.e. without message) with test of either `!isset` or `empty`.

Unclear (to me) the preferred replacement style so have not proposed a fix.

**Comment by raduconst** [comment]
@NeilWJames I proposed a fix here https://github.com/Automattic/Edit-Flow/pull/503
