### ISSUE TITLE
Archived post status reverts URL to 'preview' status

### ISSUE THREAD

**Issue by evgeniyefimchenko** [Automattic/Edit-Flow#501]
Hello. We have the same problem.
Created a new status "in the archive" and the pages disappeared from the site issue. I change the property in the theme file function.php
`function make_archived_status_public() {
  global $wp_post_statuses; $wp_post_statuses['v-arhive']->public = true; 
}
 add_action( 'init', 'make_archived_status_public');`
After this, the posts became visible, but all their links changed their appearance.
Must be `https://allbriz.ru/gelendzhik/hotel/otel-valensiya/`
It became after the change of status `https://allbriz.ru/?p=34611&post_type=object&preview_id=34611`
How can this problem be solved?

**Comment by cojennin** [comment]
Custom Statuses are used for creating workflows, they're not intended to support post visibility. Have you considered using a Tag or Category to mark a post as "in the archive" instead of a status?
