### ISSUE TITLE
"Pitch" status turns to "Draft" on save

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/Edit-Flow#514]
Steps to reproduce:

1) Create new post
2) Hit save with "Pitch" selected
3) Notice that "Draft" is the post status now instead of "Pitch".

**Comment by mikeyarce** [comment]
I wasn't able to reproduce this on Master.

![Screen Capture on 2019-08-19 at 14-20-24](https://user-images.githubusercontent.com/3220162/63300224-8db26700-c28c-11e9-9b1b-50b1f3f1859a.gif)

@rebeccahum are you still seeing this issue?  Am I missing something when I try to reproduce?

**Comment by rebeccahum** [comment]
@mikeyarce Yup, I'm still able to reproduce -- I guess I forgot to mention that I'm reproducing on the Gutenberg editor though.  I just tried via Classic Editor and it WFM.
