### ISSUE TITLE
JS can't find variable

### ISSUE THREAD

**Issue by thesquaremedia** [Automattic/Edit-Flow#522]
getting this JS error ReferenceError: Can't find variable: current_user_can_publish_posts

Keep in mind the custom status feature isnt enabled but the action_admin_enqueue_scripts is still loading. I feel like it has to do with this code below. seems like maybe however that is being unhooked and rehooked. is happening without checking if the module custom statuses is enabled or not. so its rebooking something that it shouldn't.

/**
	 * Define the hooks that need to be unhooked/rehooked to make the module Gutenberg-ready.
	 *
	 * @var array
	 */
	protected $compat_hooks = [
		'admin_enqueue_scripts' => 'action_admin_enqueue_scripts',
	];

**Comment by mjangda** [comment]
Confirmed that this is broken.

Reproduction steps:

1. Disable block editor (by installing Classic Editor)
1. Disable "Custom Statuses" module
1. Editing a post will throw the error.
