### ISSUE TITLE
Block Editor: "Extended Post Status" shown even when disabled

### ISSUE THREAD

**Issue by mjangda** [Automattic/Edit-Flow#533]
To reproduce:

1. Make sure Block Editor is enabled
1. Disable Custom Statuses
1. Edit a draft.
1. "Extended Post Status" is visible under "Document" sidebar but shouldn't be.

**Comment by cojennin** [comment]
This looks fixed with #537?

**Comment by cojennin** [comment]
Closing, but can re-open if it still needs work
