### ISSUE TITLE
preview_nonce removed unconditionally causing the Preview functionality to not work

### ISSUE THREAD

**Issue by valdezm** [Automattic/Edit-Flow#549]
The personal preview conditional isn't working, our site no longer has preview capabilities since preview_nonce never appears since the add_filter:
`add_filter( 'preview_post_link', array( $this, 'fix_preview_link_part_three' ), 11, 2 );`
hijacks the preview_nonce always. 

We have to revert this plugin back in order to have our Editors the ability to preview their work before publishing.

This block of code is unconditionally removing preview_nonce:
public function fix_preview_link_part_three( $preview_link, $query_args ) {
if ( $autosave = wp_get_post_autosave( $query_args->ID, $query_args->post_author ) ) {
foreach ( array_intersect( array_keys( _wp_post_revision_fields( $query_args ) ), array_keys( _wp_post_revision_fields( $autosave ) ) ) as $field ) {
if ( normalize_whitespace( $query_args->$field ) != normalize_whitespace( $autosave->$field ) ) {
// Pass through, it's a personal preview.
return $preview_link;
}
}
}
return remove_query_arg( [ 'preview_nonce' ], $preview_link );
}

Please advise

**Comment by mjangda** [comment]
Thanks for the report; we'll take a look.

**Comment by rebeccahum** [comment]
Hi! Can you please provide steps on reproducing? Thanks!
