### ISSUE TITLE
edit-flow.php missing headers

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/Edit-Flow#550]
The file edit-flow.php is missing a header. This was deliberately removed in https://github.com/Automattic/Edit-Flow/commit/7b8f449aaca24e142e9333d204606776bd39a7df

Removing these headers breaks the plugin for VIP clients:

```
The plugin edit-flow/edit-flow.php has been deactivated due to an error: The plugin does not have a valid header.
```

**Comment by cojennin** [comment]
Yea, we've got the same problem as [Restricted Site Access](https://github.com/10up/restricted-site-access).

The simplest fix is to load like `wpcom_vip_load_plugin( 'edit-flow/edit_flow.php' );`

Headers in both `edit-flow.php` and `edit_flow.php` won't work, we're just going to have [this issue again](https://github.com/Automattic/Edit-Flow/pull/530)

**Comment by paulschreiber** [comment]
Release 1.0 with `edit_flow.php` removed. You can make a breaking change like that since you're bumping the major version number.

**Comment by cojennin** [comment]
That's a thought, though it would end up deactivating Edit Flow on the upgrade. In the meantime `wpcom_vip_load_plugin( 'edit-flow/edit_flow.php' );` should work for folks on VIP. Same thing folks on VIP do for [Restricted Site Access](https://github.com/10up/restricted-site-access)

**Comment by cojennin** [comment]
Closing for now, can revisit later
