### ISSUE TITLE
Causes duplicate custom fields to be created

### ISSUE THREAD

**Issue by jsit** [Automattic/Edit-Flow#588]
## Steps to Reproduce the Problem

1. Activate the Edit Flow plugin
1. Add a Custom Field to a post
1. See that the Custom Field is added twice

<img width="965" alt="Screen Shot 2020-01-28 at 12 10 58 PM" src="https://user-images.githubusercontent.com/643417/73287638-8bebb880-41c7-11ea-8665-efc428ba5049.png">

**Comment by cojennin** [comment]
@jsit Hm, that's a problem. #591 should hopefully fix

**Comment by cojennin** [comment]
Fixed in Edit Flow 0.9.5
