### ISSUE TITLE
HTML garbage in "Editorial Metadata" post screen options

### ISSUE THREAD

**Issue by jsit** [Automattic/Edit-Flow#589]
1. Click the "three-dot"/"kebab" menu while editing a post
1. Click "Options"
1. See that the "Editorial Metadata" option has some HTML spillage

<img width="705" alt="Screen Shot 2020-01-28 at 11 48 12 AM" src="https://user-images.githubusercontent.com/643417/73287902-ff8dc580-41c7-11ea-8ee2-e7f6273edf74.png">

**Comment by WPprodigy** [comment]
Ah, yeah I saw this earlier today but forgot to open up an issue. Thanks.

This is automatically pulled in from metaboxes. Seems EF has some custom html in the title to link out to the settings page. The proper fix here will be to drop the metabox in Gutenberg and have the UI built for the block editor.

Temporarily though, might be able to find a way to add this HTML some other way to the metabox that doesn't inject it into where Gutenberg pulls the title from.
