### ISSUE TITLE
Saving a post does not work with WP 5.4

### ISSUE THREAD

**Issue by unitb-ore** [Automattic/Edit-Flow#598]
## Expected Behavior

The post is saved.

## Actual Behavior

An error popup appears. Error message:
`
ah@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:109:220
Ti@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:145:153
unstable_runWithPriority@https://<domain>/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:340
Ma@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:280
Ia@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:140:409
ze@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:118:14
mg/<@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:53:49
unstable_runWithPriority@https://<domain>/wp-includes/js/dist/vendor/react.min.js?ver=16.9.0:26:340
Ma@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:280
mg@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:498
V@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:52:431
Be@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:119:77
xi@https://<domain>/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.9.0:39:175
`

## Steps to Reproduce the Problem

Edit a non-published post and save it.

## Additional notes

After downgrading to WP 5.3 it works again.

Thanks for your work! I hope to see a fix soon. ;-)

**Comment by cojennin** [comment]
I'm unable to recreate this behavior with the latest version of Edit Flow and WP 5.4. [Here's a screen capture to demonstrate](https://imgur.com/a/L6ArHmi). Can you please provide more details on the plugins and themes you're using? Have you tried disabling all other plugins but Edit Flow and reverting to a default theme to see if the problem persists?

**Comment by unitb-ore** [comment]
I use a lot of plugins and a custom theme (based on the Timber default theme).

- I switched to the default theme "Twenty Twenty" now.
- I disabled all plugins except "Edit Flow".

The error still occurs.

What I forgot: After disabling Edit Flow, saving the post and enabling Edit Flow again, I was able to save the post.

It also works for newly created posts.

Maybe important: The error occurs when trying to save a post, which has been created with WP 4 (Classic editor). (I just upgraded to WP 5.x.)

What I found out right now: When I try to save the post multiple times, then sometimes it works.

**Comment by unitb-ore** [comment]
Oh... interesting: When I click "save" as quick as possible after reloading the edit page, then it works. When I wait, then it (in most cases) doesn't work.

Means: When I click "save" before the page reload is completed, then it works. Maybe something is being loaded (AJAX!?) by WP, which breaks it. The only thing I can see to appear a bit later is the "author" select box (right above the "Extended Post Status" select box, which appears immediately).

**Comment by cojennin** [comment]
Thanks for providing that information. I created a post in WP 4.9.13, then upgraded to WP 5.4 and was able to save the post again without error, [see my screen capture](https://imgur.com/a/X8czJlJ). Note that in the screen capture I opened the console to see if there were any errors on save, but saw no errors.

Are you able to use the inspector to see if you're getting any errors when you save, and if so can you post a screenshot of that here?

Also, are you using the version of [Edit Flow on wordpress.org](https://wordpress.org/plugins/edit-flow/)? If possible, could you try using the `master` branch of Edit Flow from this Github repository and see if that fixes the isuse?

Thanks!

-Connor

**Comment by unitb-ore** [comment]
Thanks for you help!

Here is the error output of the console:

![grafik](https://user-images.githubusercontent.com/8627609/78382203-be0a0400-75d6-11ea-8bde-d2fa20e60b33.png)

Yes, I installed the plugin using the WP Admin. I will try the GitHub version.

**Comment by unitb-ore** [comment]
Same error with the master version from GitHub.

Maybe helpful: I removed all states except "draft" ("Entwurf" in german) and added two custom states:

![grafik](https://user-images.githubusercontent.com/8627609/78383412-a16ecb80-75d8-11ea-8fe5-edf8b7c7a4a5.png)

**Comment by cojennin** [comment]
Hm, still having difficulty recreating the issue.

If possible, can you add `define( SCRIPT_DEBUG, true )` to your wp-config.php and send over another screenshot of the error you saw in the console? Hopefully it'll show up un-minified and give us some information.

Thanks!
-Connor

**Comment by unitb-ore** [comment]
Here is the screenshot:

![grafik](https://user-images.githubusercontent.com/8627609/78541520-0a7f5a80-77f6-11ea-9caf-88c542ce3e19.png)

![grafik](https://user-images.githubusercontent.com/8627609/78541705-592cf480-77f6-11ea-976d-0a3a915c9750.png)

**Comment by unitb-ore** [comment]
Any idea? Otherwise I have to switch to another plugin for managing custom post states. :-(

**Comment by unitb-ore** [comment]
After updating to 0.9.6 (via WP-Admin) ... it works! :) 👍 

I think, this fix could be the reason:
https://github.com/Automattic/Edit-Flow/pull/604

**Comment by cojennin** [comment]
Great to hear! Yes, I meant to update this issue with the note that #604 seemed like the fix. Glad it's working! Going to close this out now, but please let us know if you have any other issues.

Thanks!
-Connor
