### ISSUE TITLE
PHP 8.0 Plugin Compatibility - test_story_budget_set_number_days_filter_invalid

### ISSUE THREAD

**Issue by htdat** [Automattic/Edit-Flow#639]
## Expected/Desired Behavior

No issue with PHP 8.0 in the plugin.

## Actual Behavior

This test fail can be seen here https://github.com/htdat/Edit-Flow/runs/2434962761
When running PHPUnit tests, this is the error: 

```
> @php ./vendor/bin/phpunit --testsuite WP_Tests
  
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

.......................................................F...       59 / 59 (100%)

Time: 2.77 seconds, Memory: 32.00 MB

There was 1 failure:

1) WP_Test_Edit_Flow_Story_Budget::test_story_budget_set_number_days_filter_invalid
Failed asserting that 'not days' matches expected 1.

/home/runner/work/Edit-Flow/Edit-Flow/tests/test-edit-flow-story-budget.php:92
``` 

## (Optional) Additional notes

Tests fail with: 
- PHP 8.0 and WP 5.6
- PHP 8.0 and WP 5.7

**Comment by htdat** [comment]
The error around here: 

https://github.com/Automattic/Edit-Flow/blob/fbb9cbfcf08aedc0a56212bb0e67281f2e35c0fe/modules/story-budget/story-budget.php#L232-L237

A quick fix is to convert `$new_filters['number_days']` to integer like the following before passing it to the lines above: 

```php
			$new_filters['number_days'] = intval( $new_filters['number_days'] );
```

**Comment by mikeyarce** [comment]
@htdat what is changing in PHP8 that's causing the test to fail?   
What is the `test_story_budget_set_number_days_filter_invalid` test supposed to catch and where could this happen?

**Comment by htdat** [comment]
@mikeyarce Good questions! 

> What is the test_story_budget_set_number_days_filter_invalid test supposed to catch and where could this happen?

This is `test_story_budget_set_number_days_filter_invalid` that tries to set an invalid value (string) to `$new_filters['number_days']` and expect that this value falls back to `1` rather than the invalid value: 

http://github.com/Automattic/Edit-Flow/blob/124c3cde900c22abe15c04b0b2bd11e306b2aef4/tests/test-edit-flow-story-budget.php#L88-L92

> what is changing in PHP8 that's causing the test to fail?

The change happens in how the non-strict comparisons convert types of two operands: one string and one integer: 

- PHP < 8.0: "one operand is a number and the other one is a numeric string, then the comparison is done numerically".
- PHP >= 8.0: "Non-strict comparisons between numbers and non-numeric strings now work by casting the number to string and comparing the strings."

That's why I proposed to cast `$new_filters['number_days']` to an integer before doing the comparison. 

Relevant links: 
- https://wiki.php.net/rfc/string_to_number_comparison
- https://www.php.net/manual/en/migration80.incompatible.php

**Comment by mikeyarce** [comment]
This approach sounds good!   

Question: Is `intval()` better than `(int)`? Or does it really matter?

**Comment by htdat** [comment]
@mikeyarce Good question! Actually, there is no much difference between them. 
I did not use `(int)` as it did not work when I tried but it seems that I was wrong. 

From https://www.php.net/manual/en/language.types.integer.php, both should be the same: 

> To explicitly convert a value to int, use either the (int) or (integer) casts. However, in most cases the cast is not needed, since a value will be automatically converted if an operator, function or control structure requires an int argument. A value can also be converted to int with the intval() function.

Looking at https://www.php.net/manual/en/function.intval.php, this function provides another optional parameter: 

> intval ( mixed $value , int $base = 10 ) : int

In summary, using either of them is OK and there is no difference in what we're trying to fix here.
