### ISSUE TITLE
PHP 8.0 - PHPCS tests - incompatibility with vipwpcs and wpcs 

### ISSUE THREAD

**Issue by htdat** [Automattic/Edit-Flow#646]
## Summary 

squizlabs/php_codesniffer - as a part of `automattic/vipwpcs` is causing the following error: 

```
PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in /home/runner/work/Edit-Flow/Edit-Flow/vendor/squizlabs/php_codesniffer/src/Files/File.php:1056
``` 

As mentioned in https://github.com/Automattic/Edit-Flow/issues/638#issuecomment-825511819, the issue in WPCS: 

> Relevant issue https://github.com/squizlabs/PHP_CodeSniffer/issues/3196
It has been fixed here https://github.com/WordPress/WordPress-Coding-Standards/pull/1935
But WPCS ver 3.0.0 including this fix has not been released. 

## Next 

Wait for the new release of WPCS 3.0.0 and see if the issue still exists.

**Comment by jerclarke** [comment]
Hey @htdat Can you give me a sense of whether this plugin is alive for public release or not? Are you planning to release a stable version at some point?

**Comment by htdat** [comment]
@jerclarke - We have tried to improve our tests and make the plugin more stable when fixing bugs or adding new features. So far, we're not yet having a formal plan for the next stable release.

**Comment by jerclarke** [comment]
Glad to hear about the testing at least. I guess I'll try updating to the latest master and see if it works for my needs or not. Trying to avoid switching to another plugin if I don't have to.
