### ISSUE TITLE
Mail not getting sent due to checkbox

### ISSUE THREAD

**Issue by iamkingsleyf** [Automattic/Edit-Flow#675]
Hi,

Some years ago when you publish a post it gets sent to the contributor without MARKING THE CHECKBOX, now updates don't get sent if the CHECKBOX is left unmarked before clicking the publish button.

Regards

**Comment by mikeyarce** [comment]
Hi @iamkingsleyf can you give us some steps to be able to reproduce this?  Thanks!

**Comment by iamkingsleyf** [comment]
Hi @mikeyarce don't check the box for the contributor and click publish, the contributor account won't receive email.
i don't even receive emails for my own article

**Comment by mikeyarce** [comment]
Hi @iamkingsleyf - I think I understand what you mean, can you tell me if this is right?

1. Create a new post, logged in as Author 1
2. In the Notification section, make sure Author 1 is NOT selected
3. Publish the post
4. Author 1 will not be notified

That seems to be the right behaviour, not selecting Author 1 should mean that they don't get notifications.  If you do select them in the Notifications section, do you get an email?

It might be that this was a previous bug that was fixed?

**Comment by iamkingsleyf** [comment]
> Hi @iamkingsleyf - I think I understand what you mean, can you tell me if this is right?
> 
> 1. Create a new post, logged in as Author 1
> 2. In the Notification section, make sure Author 1 is NOT selected
> 3. Publish the post
> 4. Author 1 will not be notified
> 
> That seems to be the right behaviour, not selecting Author 1 should mean that they don't get notifications. If you do select them in the Notifications section, do you get an email?
> 
> It might be that this was a previous bug that was fixed?

Yes you are correct, we have fix the notification issue in previous issue can't remember it

**Comment by iamkingsleyf** [comment]
> One more thought, if the filter `ef_notification_email_current_user` is set to true, then it will always email the "current author" - maybe that's what you need? From:
> 
> https://github.com/Automattic/Edit-Flow/blob/2e07a1b7b7af1e783b858700390da85b418c2405/modules/notifications/notifications.php#L889
> 
> Example:
> 
> ```
> add_filter( 'ef_notification_email_current_user', '__return_true' );
> ```

I guess, because sometimes i forget to check the box, even though i need the user to be notified.
Where should i place the code?

**Comment by mikeyarce** [comment]
> I guess, because sometimes i forget to check the box, even though i need the user to be notified.
Where should i place the code?

You can place the filter in your themes `functions.php` file.

I just tested it out and if that filter is set to true, then if you select the main author to receive notifications, the notifications are sent to the author.
