### ISSUE TITLE
Bug: Post date gets set after saving a new draft instead of remaining floating 

### ISSUE THREAD

**Issue by amyevans** [Automattic/Edit-Flow#676]
## Expected Behavior

The `Publish` value on a newly created post should say `Immediately` (remain "floating"), unless it is explicitly set by the user or created from the calendar view of the Edit Flow calendar module.

## Actual Behavior

The post date on the post gets locked in as soon as you save the draft.

## Steps to Reproduce the Problem

1. Enable the Edit Flow Calendar module
1. Add a new post
1. Click "Save draft"

## Additional notes

This seems similar/related to #623 perhaps, but not exactly the same.

#### Screenshots
**Behavior with Edit Flow calendar module:**
_Before save_
![EF Calendar bug - before save](https://user-images.githubusercontent.com/7277067/125965747-6bf88d2a-f75f-4925-bf68-31e2fbde25a4.png)
_After save_
![EF Calendar bug - after save](https://user-images.githubusercontent.com/7277067/125965758-8213da61-ab9c-4c33-b285-88057d14122d.png)

**Behavior without Edit Flow calendar module:**
_Before save_
![Without EF Calendar - before save](https://user-images.githubusercontent.com/7277067/125965715-69d5c50d-3cdc-403c-b675-c47131ee173c.png)
_After save_
![Without EF Calendar - after save](https://user-images.githubusercontent.com/7277067/125965733-75acc654-07ff-4a82-9169-adeef0aef855.png)

**Comment by mikeyarce** [comment]
@DustinHartzler can you take a look at this one?

**Comment by amyevans** [comment]
Going to close due to inactivity
