### ISSUE TITLE
Public version release needed for PHP 8 Compatibility

### ISSUE THREAD

**Issue by mslinnea** [Automattic/Edit-Flow#686]
## Expected/Desired Behavior

1. Plugin release for a PHP 8 compatible version of this plugin.

## Actual Behavior

We are using the latest public release of this plugin, and it's being flagged for PHP 8 compatibility issues. Looking into this, we found that it actually was updated for PHP 8 in https://github.com/Automattic/Edit-Flow/pull/627

However, there was never a release made after this update. [WP Packagist](https://wpackagist.org/search?q=edit-flow&type=any&search=) and [WordPress.org Plugin repo](https://wordpress.org/plugins/edit-flow/) are showing the last release as 0.9.6, which doesn't have these PHP 8 compatibility fixes.

To work around this issue, we had to change our composer dependency from wpackagist-plugin/edit-flow": "^0.9.6" to "automattic/edit-flow": "dev-master"

**Comment by amandasjackson** [comment]
152473-zen

**Comment by rebeccahum** [comment]
This has been released now: https://github.com/Automattic/Edit-Flow/releases/tag/0.9.7
