### ISSUE TITLE
Version number needs to be updated for 0.9.8

### ISSUE THREAD

**Issue by attackant** [Automattic/Edit-Flow#713]
https://github.com/Automattic/Edit-Flow/blob/113554f8167ed2cea926687d1a7b963d59c28f6f/edit_flow.php#L7C11-L7C15

**Comment by UTCGilligan** [comment]
@rebeccahum Will the version be updated in a re-release?

**Comment by rebeccahum** [comment]
Ah sorry, thanks for that catch. I'll re-issue that.
